name: Generator Workflow

on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight UTC

jobs:
  generator:
    runs-on: ubuntu-latest

    steps:
    - name: Setup shell
      uses: actions/setup-shell@v2

    - name: Made-by text
      id: madeby
      run: echo "Made-By: DeclanMiner2005 (DeclanCommunity)" >> seabird.txt

    - name: Version text
      id: version
      run: echo "Version: $(date +"%Y.%m.%d")" >> seabird.txt

    - name: Hex data
      id: hextxt
      run: sh -c 'echo -n "AA BB CC DD EE FF 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0F 0E A0 B0 C0 D0 E0 F0" > hex.txt'
