name: Multi-language Workflow

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Download Ducky Image
      - name: Download Ducky Image
        uses: actions/download-artifact@v2
          name: ducky-image
          download-url: https://boonk8812.github.io/actionsimages/ducky@v1.img

      # Set up Python and Java environments
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          pip: true

      - name: Install OpenJDK
        uses: actions/setup-java@v2
        with:
          java-version: openjdk-11

      # Test Math module
      - name: Test Math Module
        run: |
          python --version
          python -m unittest discover tests/math/*.py

  download_legacy_python:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      # Download three random legacy Python versions
      ...
      
  run_ccpp:
    needs: download_legacy_python
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      ...

      # Build and run c-cpp.yml
      - name: Run c-cpp.yml
        uses: ./.github/workflows/c-cpp.yml
